### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by AJAnderson**
I found the URLs for importing in OBS MP by looking at OBS, I'm assuming you could also infer them from looking at the dir but perhaps you could clarify that part?

### CODE REVIEW

**Comment by AJAnderson** [comment]
Ok, updated with some gotchas when using with MP, such as the fact that scene transitions won't work.

**Comment by mparkms** [comment]
Thanks for that. You can also find the URLs by going into the graphics page from the menu in the dashboard. I'll update that myself.

**Comment by AJAnderson** [comment]
Hi Mike,

Was just wondering if you know how to change the font used for e.g. player
names, etc.

Kind regards,
Alex

**Comment by mparkms** [comment]
The default font uses [Google Fonts](https://www.google.com/fonts). You can either use that (there's a script tag at the beginning of every graphics html file you switch out, then just change the font name in the CSS) or you can download your own fonts, put them in the graphics folder, and add them in the CSS files using `@font-face`.

**Pull request merged**
